DROP TABLE EMPLOYEES IF EXISTS;

CREATE TABLE EMPLOYEES (
  id VARCHAR(30)  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(100) DEFAULT NULL
);
DROP TABLE MATERIAL_EMPLOYEE IF EXISTS;

CREATE TABLE MATERIAL_EMPLOYEE (
	id_employee INT,
	id_element INT
);

DROP TABLE MATERIALS IF EXISTS;

CREATE TABLE MATERIALS(
	  id INT AUTO_INCREMENT  PRIMARY KEY,
	  description VARCHAR(250) NOT NULL
);

DROP TABLE ROLES IF EXISTS;

CREATE TABLE ROLES (
	id INT PRIMARY KEY,
	name VARCHAR(10) DEFAULT NOT NULL,
	description VARCHAR(50) DEFAULT NOT NULL
);

INSERT INTO ROLES VALUES (1, 'admin', 'Administrator of the system');
INSERT INTO ROLES VALUES (2, 'rrhh', 'HR of the company');
INSERT INTO ROLES VALUES (3, 'employee', 'One employee of the company');